language: ruby
rvm:
  - 2.6.3

script: "./script/cibuild.sh"

deploy:
  provider: s3
  access_key_id: AKIAQ2QXIVZXMMO7QEHR
  secret_access_key:
    secure: GJeoDiNki/JX4SQbs+KsTeD1YwUmT84h7cJu2/OL/k2xB7WSFHt9XWeWUWb8ied7Y1hCvdcSxx/UMPpMWkzsrOlx+uksG7yZ+cxYnofVymXA7i1ZDw9UUK51Kswnv9QN/TYWGBMb8eH9SJOkHvS+3he1TDGz5wtqKxOoLnqTkeVt/UNqjNQxTH85BivGSi5kwCZMWuUBtlTtkbc86qcO/rc6G9ROf4ZjxzrMofHZcE17q9vWle5YiT8JX4WFXu8XvSRmei+giKuIMakM42WQ1GOZhIzIuhFoAzvh5L9vCXyXK7AQzyejlX7Cy5D1Q16FLBfrZTrF/w+qfx9hIJZP6erVrYoWfF76JTWgSpTej570pc+Rp4gxmwfAzC163jEzgE+aBCOTV2yQ48fKXWIfHgH4QKUqdMJSLCbXhX9ffkYtpr0Alq0Z0JqqWL4MYmElTJVNhbEINYQF2OIM1JEh9eXQdQBvTEzvhliolql/5ZB71LKO0BEW87RUSql5QzEUZ/H3yGEWMnbdofh7gJUR4bi6he7g62N1svQI5uCLndsE94TprxEibc0Ce1nULHmXhj1wf3c7nGOkxSi2/sRgzHmRwTxAFm3Ey1n7ZsY9Ur7BYjQN7kVHmeronOp5qH7enZ6KWqJJBhZg44TS5pp0eKcjZNqiylkMBkyNzZc8AzU=
  bucket: www.leonpahole.com
  local_dir: _site
  skip_cleanup: true
  on:
    tags: true

branches:
  only:
    - master

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

addons:
  apt:
    packages:
      - libcurl4-openssl-dev

sudo: false

cache: bundler
