language: ruby
rvm:
  - 2.6.3
script: "./script/cibuild.sh"
deploy:
  provider: s3
  access_key_id: AKIAQ2QXIVZXMMO7QEHR
  secret_access_key:
    secure: eLlcnkJQmK6WeVYZoyMChTNmzgs8Z5BKnSdefvWxl7ufJKw7vMIeX5WdH7p40GgWT1DTILs4NQ9X5SgjrdrV37SNbQ5iMQULzFxII3fyRGOTC7osWGM1auPhkLr6kPJzjdooPvQifR4h4LKpV/hn0Q9Jrrz+kZUkTKmVJCz4LO0Ejopt/8RM3pePECj0eyO87oUCze2rpjoFC6bCzdxylN3Z7/apS2o1DMAvDsGRXPnV++t2lagcTSTdh472BqeGDHrYsCnI7GYnIMn6+V6V4Xyxd1eXRqiFRUwS7mSUxMnicMC/YUNwn+tImtdn0wcxfl0cSb6s0qkP8QemyqwBgk7PJWCnxEEwOqR9iZ6H3VcYTm+q9oQuPNyVVnGTemWNy2a2XC0OcLBBmtWm2C9SZyp2jvBPUzoRv34CVpl3lsdl1/miWCGBJ59loHUtsm5H9dwFtDpM5RTTVVCkCUNQRaq184q8qy/zMtQpNKKHO4gOLdJz8/Pyg/p09zPMyPyuq0dj1fanwp6iwwDIgV4OUBS9X7RpVMqXAaIyyZ8irClpk039p4rAN8aOy0jTJtfc5jcdPGRt1NpFCiPKYM/0IxPSeHI7JY0G8bqCAo8R3KdyvUytmc+0CYlv07u4XE45mKFfg7db+Eh7SQrXtXRWcCP0mACzBWxr48OPVi86Ekw=
  bucket: www.leonpahole.com
  local_dir: _site
  skip_cleanup: true
  on:
    repo: leonpahole/leonpahole-com

branches:
  only:
    - master
    - "/^v.*$/"
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
sudo: false
cache: bundler
